name: Linting
on: [push]
jobs:
  writing-guidelines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get added and modified files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint with Vale
        uses: errata-ai/vale-action@v1.3.0
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          files: '${{ steps.files.outputs.added_modified }}'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
